lacework/terraform-aws-cloudtrail

main.tf
- Added logic to gracefully handle a trailing slash in the `bucket_arn` variable.
=> fix(aws): gracefully handle trailing slash in bucket_arn

README.md, main.tf, variables.tf
- Added the ability to toggle 'mfa_delete' for the S3 storage bucket.  This requires versioning to be enabled.
=> feat: support for 'mfa_delete' variable

main.tf, variables.tf
- `mfa_delete` is dependent on `versioning`, so logic is improved to AND together those variables.
- `mfa_delete` default changed to false
=> fix: improved logic for `mfa_delete` variable

examples/existing-cloudtrail-without-sns-topic/README.md
This PR updates the link to the gif for manually attaching SNS topic to existing CloudTrail
Signed-off-by: Scott Ford <scott.ford@lacework.net>
=> docs: Fix link to sns gif

README.md, examples/existing-cloudtrail-iam-role/README.md, examples/existing-cloudtrail-iam-role/main.tf, examples/existing-cloudtrail/README.md, examples/existing-cloudtrail/main.tf, examples/existing-encrypted-cloudtrail/README.md, examples/existing-encrypted-cloudtrail/main.tf, main.tf, output.tf, variables.tf
```hcl
use_existing_cloudtrail = true
bucket_arn              = "arn:aws:s3:::lacework-ct-bucket-8805c0bf"
bucket_name             = "lacework-ct-bucket-8805c0bf"
sns_topic_name          = "lacework-ct-sns-8805c0bf"
```
```hcl
use_existing_cloudtrail = true
bucket_arn              = "arn:aws:s3:::lacework-ct-bucket-8805c0bf"
bucket_name             = "lacework-ct-bucket-8805c0bf"
use_existing_sns_topic = true
sns_topic_arn          = "arn:aws:sns:us-west-2:123456789012:lacework-ct-sns-8805c0bf"
```
When switching formats to take advantage of the `ARN` rather than an account/region-specific `Name`, the user of this module must remove the Terraform state for the previously imported SNS Topic and SNS Topic Policy - otherwise, Terraform will attempt to delete those resources.  To do this, the …
=> feat: allow explicit use of an existing SNS topic

output.tf
We were never outputting the actual IAM Role name since we were referencing the variable
defined as `var.iam_role_name` rather than the local variable which has logic to pass the
right variable to the consumer. (that is `local.iam_role_name`)
Closes https://github.com/lacework/terraform-aws-cloudtrail/issues/44
=> fix: output reference to local iam_role_name variable

.github/pull-request-template.md
Signed-off-by: Darren Murray <darren.murray@lacework.net>
External contributors will not have access to Jira; include Github as another relevant source for the issue link.
=> docs: Include 'Github' as relevant issue link

README.md, main.tf, variables.tf
---
name: Use existing access log bucket option
about: 'feat(module): Add use of existing access log S3 bucket'
---
***Issue***
https://github.com/lacework/terraform-aws-cloudtrail/issues/56
***Description***
Adding a `use_existing_access_log_bucket` flag which will prevent the default access logs bucket from being created.
Adding an `access_log_prefix` to control logging prefix in said log bucket.
The default logging bucket should only be created if `use_existing_cloudtrail` and `use_existing_access_log_bucket` are both false and if `bucket_enable_logs` is set to true.
To control the selection of the existing log bucket the already created `log_bucket_name` variable will be used. 
The `access_log_prefix` will be defaulted to "logs/" but can be changed.
=> feat: Use existing access log bucket option

README.md
***Issue***: https://lacework.atlassian.net/browse/ALLY-777
Correct `use_existing_access_log_bucket` description. Which when true requires `log_bucket_name` not `access_log_bucket_arn`
=> docs: Fix incorrect use_existing_access_log_bucket description

README.md
***Issue***: https://lacework.atlassian.net/browse/ALLY-776
`use_existing_cloudtrail` description says 'if true bucket_name must be specified'.
Update  use_existing_cloudtrail`bucket_name` to remove line 'When set to `true` you must provide the `bucket_name`'
=> docs: Fix incorrect use_existing_cloudtrail description

README.md, examples/complete-cloudtrail/main.tf, main.tf, variables.tf
This change requires major version bump
***Issue***:  https://lacework.atlassian.net/browse/ALLY-740
Variable defaults should not violate compliance rules
Changes to default settings
```
`enable_log_file_validation`: true
`bucket_enable_logs`: true
`bucket_enable_versioning`: true
`bucket_enable_encryption`: true
```
Todo update documentation for `bucket_enable_mfa_delete` -> detail that compliance will fail LW_S3_12 unless enabled
=> feat: ensure resources adhere to Lacework compliance rules

main.tf
Logical binary operators don't short-circuit: https://github.com/hashicorp/terraform/issues/24128
In terraform, logical binary operators don't short-circuit: https://github.com/hashicorp/terraform/issues/24128
So while the code here looks like each branch of the conditional check is checking to see whether the second check is necessary, terraform (or more strictly/accurately, HCL) is always evaluating all of the branches of the boolean expression.
The problem with that is that, for example, if you _don't_ need to check the `var.bucket_sse_key_arn` because `var.use_existing_cloudtrail` is true, but your `var.bucket_sse_key_arn` that you passed in is referencing another resource, this will create a terraform error because it can't determine the ultimate value of this `create_kms_key` local …
=> Use ternary instead of && for boolean logic

README.md, main.tf, output.tf, variables.tf
This PR allows the creation of the CloudTrail integration in Lacework to be optional, and provides all required parameters as outputs in the module.  This is done to allow extensibility in how the integration is created.
Tested this change in my AWS organization.
N/A
=> feat: allow Lacework integration creation to be optional

versions.tf
Signed-off-by: Darren Murray <darren.murray@lacework.net>
Set lacework provider to minimum version for api v2 migration
https://lacework.atlassian.net/browse/ALLY-1193
=> fix: set lacework provider to minimum version for api v2 migration

main.tf
The variable `use_existing_access_log_bucket` was not being handled correctly in `aws_s3_bucket_logging` resource
If variable `use_existing_access_log_bucket` is true set target_bucket to use local variable else use newly created bucket
https://lacework.atlassian.net/browse/ALLY-1291
=> fix: handle use_existing_access_log_bucket correctly in aws_s3_bucket_logging resource

main.tf
CI should pass! 🤞🏽 
Fixes https://github.com/lacework/terraform-aws-cloudtrail/pull/103
=> fix: use valid module argument permission_boundary_arn

examples/existing-cloudtrail-without-sns-topic/README.md, examples/existing-cloudtrail-without-sns-topic/main.tf, main.tf
AWS changes the policy when a new SNS topic is attached to an existing CloudTrail.  This change updates the policy in the HCL to match.
1) Run `terraform apply` in `examples/existing-cloudtrail-without-sns-topic`
2) Add the created SNS topic ARN to the existing CT
3) Run `terraform plan`
https://github.com/lacework/terraform-aws-cloudtrail/issues/110
https://lacework.atlassian.net/browse/GROW-1498
=> fix: SNS policy to match attachment update

README.md, main.tf
To enable bucket ACL the `ObjectOwnership` parameter must be set to `ObjectWriter`.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html
https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/
https://g.codefresh.io/build/64391961e8a80758c043e517?step=TerraformPlan&tab=output&logs=terminal
https://lacework.atlassian.net/browse/GROW-1534
=> fix: s3 bucket ownership controls

main.tf
It is possible for the S3 bucket ACL resource to be created before the ownership controls, leading a failure to apply the ACL.  We need to define an explicit dependency.
https://g.codefresh.io/build/6480402325053f6cc74dc5fa no changes in TF plan.  This code change just sets order of the creation of resources.
https://lacework.atlassian.net/browse/GROW-1835
=> fix: S3 bucket ACL dependency

main.tf
`cloudtrail_log_bucket_acl` must depend on `cloudtrail_log_bucket_ownership_controls`.
https://lacework.atlassian.net/browse/GROW-1835
=> fix: ACL depend_on log bucket

DEVELOPER_GUIDELINES.md, README.md, examples/cloudtrail-existing-kms-key/README.md, examples/cloudtrail-existing-kms-key/main.tf, examples/complete-cloudtrail-access-logs-with-object-level-logging/README.md, examples/complete-cloudtrail-access-logs/README.md, examples/complete-cloudtrail-unencrypted/README.md, examples/complete-cloudtrail-unencrypted/main.tf, examples/complete-cloudtrail-versioning/README.md, examples/complete-cloudtrail/README.md, examples/complete-cloudtrail/main.tf, examples/consolidated-cloudtrail-multiple-lacework-tenants/README.md, examples/consolidated-cloudtrail/README.md, examples/existing-cloudtrail-end-to-end-encryption/README.md, examples/existing-cloudtrail-iam-role/README.md, examples/existing-cloudtrail-s3-encryption/README.md, examples/existing-cloudtrail-s3-notifications/README.md, examples/existing-cloudtrail-without-sns-topic/README.md, variables.tf
When we use this module to automatically deploy and rollback changes. Users are having
constant issues trying to destroy the S3 bucket if it is not empty. To unblock this problem,
users need to turn on the `bucket_force_destroy` flag, and then do any modification that
requires a "destroy" operation.
By default, we should allow users to do these operations without the need to know about
this flag, if users does not wish to allow these buckets to be destroyed when they are not
empty, users should switch off the flag with `bucket_force_destroy = false`.
After merge, we will run our internal pipeline https://github.com/lacework/terraform-customerdemo/pull/70
https://lacework.atlassian.net/browse/GROW-1336
=> chore: enable bucket_force_destroy by default

README.md, variables.tf
Updating the documentation to make clear that the input `cloudtrail_name` is required when `use_existing_cloudtrail` is set to true.
https://lacework.atlassian.net/browse/GROW-2292
=> fix: existing CloudTrail doc update

main.tf
Customer reported that the CloudTrail that LW created was being flagged as having a publicly accessible KMS key.
Updated the KMS policy to remove the * for the principal and added the caller
```
principals {
type        = "AWS"
identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
}
```
the new terraform was applied and the integration was successfully updated. Checking on a test AWS account the actual policy can be seen below
Integration creation was successful 
The issue is covered in a number of JIRA tickets, here 
Original Link ticket        https://lacework.atlassian.net/browse/LINK-1795
Parent Dev ticket.          https://lacework.atlassian.net/browse/GROW-2303
Ticket for this change.  https://lacework.atlassian.net/browse/GROW-2319
=> fix: KMS least privileged access

README.md, output.tf
Adds `bucket_sse_key_arn` output to allow module and resource chaining. This new output
holds the ARN of the KMS encryption key used for S3.
CI will succeed and I ran `terraform output` locally.
N/A
=> chore(output): ARN of the KMS encryption key used for S3

CHANGELOG.md
We had to do an ad-hoc release
https://github.com/lacework/terraform-aws-cloudtrail/releases/tag/v1.0.3
This change is syncing the CHANGELOG to include this version.
=> chore: update CHANGELOG with ad-hoc release

.github/workflows/nightly.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml, .github/workflows/test-compat-pr-comment.yml, .github/workflows/test-compatibility.yml, .github/workflows/verify-release.yml, scripts/ci_tests.sh
These workflows replace the codefresh workflows of the same names as Lacework is migrating off of Codefresh.
These work flows were first tested as much as possible in a non-main branch. Then in the main branch of a single terraform module (terraform-azure-activity-log). 
https://lacework.atlassian.net/browse/GROW-2760
=> ci: migrate from codefresh to github actions

main.tf
Tested locally with terraform plan
=> fix(GROW-3004): Fix the sid issue

main.tf
The following error is introduced by https://github.com/lacework/terraform-aws-cloudtrail/pull/168
```
Name: AWS CloudTrail, Status: failed, Error: failed to run terraform apply: exit status 1
Error: creating CloudTrail Trail (lacework-cloudtrail-1af4c7f3): operation error 
CloudTrail: CreateTrail, https response error StatusCode: 400, 
RequestID: 9f5cac78-22bf-4646-9645-a992d0b878d5, 
InsufficientSnsTopicPolicyException: SNS Topic does not exist or the topic policy is incorrect! 
```
Add `aws_sns_topic.lacework_cloudtrail_sns_topic` as a dependency of `aws_cloudtrail.lacework_cloudtrail` to fix it.
`terraform apply` runs correctly now.
=> fix: lacework_cloudtrail should depend on lacework_cloudtrail_sns_topic

README.md, main.tf, variables.tf
In environments where customers have managed service providers with shared access to administer kms keys there is a need to allow the lacework KMS to be provisioned (optionally) with an extended list of trusted identities.
Deployed to test environment.
Raised via customer NFR:
https://mantis.fortinet.com/bug_view_page.php?bug_id=1117782
=> feat: allow users to specify additional users for kms key policy
