lacework/terraform-aws-cloudtrail

scripts/release.sh

Signed-off-by: Darren Murray <darren.murray@lacework.net>

fix: readd removed lines in release script

---

.circleci/config.yml
README.md
examples/complete-cloudtrail/main.tf
main.tf
variables.tf

Closes https://github.com/lacework/terraform-aws-cloudtrail/issues/13

feat: support for enable_log_file_validation

---

examples/complete-cloudtrail-access-logs/README.md
examples/complete-cloudtrail-access-logs/main.tf
examples/complete-cloudtrail-versioning/README.md
examples/complete-cloudtrail/README.md
examples/complete-cloudtrail/main.tf
examples/consolidated-cloudtrail-multiple-lacework-tenants/README.md
examples/consolidated-cloudtrail/README.md
examples/existing-cloudtrail-iam-role/README.md
examples/existing-cloudtrail-without-sns-topic/README.md
examples/existing-cloudtrail/README.md

This PR updates all example scenarios with updated READMEs and links back to Lacework support docs.
Signed-off-by: Scott Ford <scott.ford@lacework.net>

docs: Update examples for all scenarios

---

.circleci/config.yml
main.tf
scripts/release.sh

Closes https://github.com/lacework/terraform-aws-cloudtrail/issues/26

fix: dependency conflicts with other tf modules

---

scripts/release.sh
scripts/release_helpers.sh

ci: update release scripts

---

.gitignore

fix(ci): ignore .terraform.lock.hcl files

---

main.tf

Issue: Add tags to IAM Policy
Description:
Adding the user provided tags to the IAM policy created by this terraform module
Additional Info:
N/A

fix: add tags to IAM Policy

---

DEVELOPER_GUIDELINES.md
README.md
examples/complete-cloudtrail-access-logs/README.md
examples/complete-cloudtrail-versioning/README.md
examples/consolidated-cloudtrail-multiple-lacework-tenants/README.md
examples/consolidated-cloudtrail/README.md
examples/existing-cloudtrail-iam-role/README.md
examples/existing-cloudtrail-s3-encryption/README.md
examples/existing-cloudtrail-s3-encryption/main.tf
examples/existing-cloudtrail-without-sns-topic/README.md
examples/existing-cloudtrail/README.md

update examples to use version `~> 1.0`

docs: update examples to use v1.0

---

main.tf

If a user brings their own CloudTrail, we assume by default that
the Bucket is encrypted so we try to apply a policy that doesn't
have a valid SSE Key ARN.
The fix we are applying is to check that the SSE Key ARN was provided
by the user, if so, bucket encryption is enabled and we apply the
policy.
Replicated the issue in a local environment.
After applying the fix, the command `terraform apply` succeeded.
https://lacework.atlassian.net/browse/ALLY-893

fix: bucket_encryption_enabled checks SSE Key ARN length

---

README.md

***Issue***: N/A (this is a small change, but happy to create a bug report if required)
- Update the README for the default value of the bucket_sse_algorithm variable

docs: update README to match bucket_sse_algorithm default

---

main.tf
variables.tf

***Issue***: N/A
Adds a new variable name `kms_key_rotation` to allow enabling KMS automatic key rotation.

feat: add kms_key_rotation variable to control KMS auto rotation

---

README.md
main.tf
variables.tf

This change is passing 1 to 1 the variable `is_organization_trail` to the `aws_cloudtrail` resource.
Jira: https://lacework.atlassian.net/browse/ALLY-941
Closes https://github.com/lacework/terraform-aws-cloudtrail/issues/80

feat: support the creation of organizational trail

---

output.tf

Adding the Lacework integration GUID to the module output to allow for future integrations.
Ran the module with the new output and verified its correctness.
N/A

feat: added Lacework integration guid to output

---

README.md
examples/existing-cloudtrail-s3-notifications/README.md
examples/existing-cloudtrail-s3-notifications/main.tf
examples/existing-cloudtrail-s3-notifications/versions.tf
main.tf
scripts/ci_tests.sh
variables.tf

This PR is meant to add support for using S3 bucket notifications, which have been added to the platform.
Tested multiple configuration scenarios in my AWS account:
- CloudTrail -> SNS
- S3 -> SNS
- S3 -> SQS
This should resolve #50 - Also, here is the internal Jira regarding S3 notification support: https://lacework.atlassian.net/browse/RAIN-26834

feat: support for S3 bucket notifications

---

examples/cloudtrail-existing-kms-key/README.md
examples/cloudtrail-existing-kms-key/main.tf
examples/cloudtrail-existing-kms-key/versions.tf
main.tf
scripts/ci_tests.sh
variables.tf

Signed-off-by: Darren Murray <darren.murray@lacework.net>
Add support for a custom kms key when creating a new cloudtrail.
Run TF apply on new example `/examples/cloudtrail-existing-kms-key`
https://lacework.atlassian.net/browse/GROW-1290

feat: allow existing kms key with new cloudtrail

---

main.tf

Remove unneeded debug permissions
https://lacework.atlassian.net/browse/GROW-1166

refactor: remove unneeded debug permissions

---

scripts/ci_tests.sh

ci: use a session token for the ci_tests

---

README.md
examples/cloudtrail-existing-kms-key/README.md
examples/complete-cloudtrail-access-logs-with-object-level-logging/README.md
examples/complete-cloudtrail-access-logs/README.md
examples/complete-cloudtrail-unencrypted/README.md
examples/complete-cloudtrail-versioning/README.md
examples/consolidated-cloudtrail-multiple-lacework-tenants/README.md
examples/existing-cloudtrail-end-to-end-encryption/README.md
examples/existing-cloudtrail-iam-role/README.md
examples/existing-cloudtrail-s3-encryption/README.md
examples/existing-cloudtrail-s3-encryption/main.tf
examples/existing-cloudtrail-s3-notifications/README.md
examples/existing-cloudtrail-without-sns-topic/README.md
examples/existing-cloudtrail/README.md
main.tf
variables.tf

Use the updated IAM role which has the new lacework_external_id resource
Ran terraform and checked that resources are created correctly with required format
https://lacework.atlassian.net/browse/GROW-2420

feat: enforce External ID v2 format via iam-role module

---

README.md
main.tf

https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-create-and-update-an-organizational-trail-by-using-the-aws-cli.html
https://lacework.atlassian.net/browse/GROW-2549

fix: org cloudtrail bucket policy

---

README.md
main.tf
versions.tf

Support lacework metrics data source
https://lacework.atlassian.net/browse/GROW-2627

feat: add lacework_metric_module datasource

---

examples/cloudtrail-existing-kms-key/README.md
examples/existing-cloudtrail/README.md

Updated two READMEs with out of date links to documentation website, which would give a page not found error
Verified links to doc
[RAIN-70541](https://lacework.atlassian.net/browse/RAIN-70541)
[RAIN-70541]: https://lacework.atlassian.net/browse/RAIN-70541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: update links to documentation RAIN-70541
